### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by bdbozyk** [BrianCopelandBz/cwaas#1]
The timestamp would be more applicable if it displayed timestamp in 12 hour clock, as well as the current time zone Carl is in.

**Comment by zsands** [comment]
The user's local time might be better so the user can gauge how long it has been since Carl drank water

**Comment by bdbozyk** [comment]
Perhaps, both Carl's time and the Users time should be displayed, along with a single bar bar chart displaying how long in minutes it has been since he drank water.

**Comment by BrianCopelandBz** [comment]
Finished, all in CST, now displays on thermometer in more human readible 12 HR format: f05079d3899a300b46beb4b8f3f114e60fd40277

**Comment by zsands** [comment]
I worry that the central time focus neglects the on the go and
international segments of the user base

**Comment by bdbozyk** [comment]
Make an international map plot with the location of user updates.
