### ISSUE TITLE
Link to main site 

### ISSUE THREAD

**Issue by bdbozyk** [BrianCopelandBz/cwaas#10]
I think efficiency can be gained if there was a link from the secret site to the main site. I waste seconds going to my bookmarks.

**Comment by BrianCopelandBz** [comment]
@bdbozyk But then Carl would know the secret site and have the ability to update his own jerk status...? Isn't that bad?

**Comment by bdbozyk** [comment]
@briancopelandbz you are thinking in the wrong direction - A link from the secret site to the main site.

**Comment by BrianCopelandBz** [comment]
Ohhhhh! Easy done, sure thing.

**Comment by bdbozyk** [comment]
Nice work.
