### ISSUE TITLE
Zach

### ISSUE THREAD

**Issue by bdbozyk** [BrianCopelandBz/cwaas#3]
The platform would benefit if all users, including Zach, submit issues through the proper channels.

**Comment by zsands** [comment]
THIS ISSUE IS DUMB

**Comment by bdbozyk** [comment]
You're Dumb.

**Comment by zsands** [comment]
If I had Brett bozyk jerk status meter app it would be so high right now

**Comment by bdbozyk** [comment]
Likewise.

**Comment by BrianCopelandBz** [comment]
Apparently, this bug fixed itself.
